name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  # Creating image in ACR 
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: servian.azurecr.io
          # Secrets are stored in project settings -> secrets
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: build and push image to ACR   
        run: |
          docker build . -t servian.azurecr.io/appdb:${{ github.sha }}
          docker push servian.azurecr.io/appdb:${{ github.sha }}
          
  deploy:     
    runs-on: ubuntu-latest
    needs: build
    steps:         
      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with: 
          creds: ${{ secrets.AZURE_SP_CREDS }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Deploy to ACI from Container registry 
        uses: Azure/aci-deploy@v1
        with:
          # Name of the Resource Group in which the Container Instance will be created
          resource-group: ServianGTD
          # The storage account access key used to access the Azure File Share
          cpu: 1
          # The DNS Name Label for Container with Public IP
          dns-name-label: gtdapp
          # Specify the fully qualified container image name. For example, "myregistry.azurecr.io//nginx:latest" or "python:3.7.2-alpine/"
          image: servian.azurecr.io/appdb:${{ github.sha }}
          # Location where the Container will be deployed
          location: australiaeast
          # Required Memory of the Containers in GB, accurate to one decimal place
          memory: 1.5
          # Name of the Container Group Instance
          name: ServianGTDApp
